backend:
  name: github
  repo: igor-anosov/dobrolikar-landing
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "pages"
    label: "Сторінки"
    files:
      - file: "index.html"
        label: "Головна сторінка"
        name: "home"
        fields:
          - { label: "Заголовок сайту", name: "hero_title", widget: "string" }
          - {
              label: "Опис послуг",
              name: "services_description",
              widget: "text",
            }
          - {
              label: "Номер телефону клініки",
              name: "phone_number",
              widget: "string",
            }
          - { label: "Текст кнопки запису", name: "cta_text", widget: "string" }
